import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tinysteps/controllers/ai_insights_controller.dart';
import 'package:tinysteps/core/constants/app_theme.dart';
import 'package:tinysteps/core/theme/theme_ext.dart';

class ChildInsightsScreen extends ConsumerWidget {
  final String childId;
  final String childName;

  const ChildInsightsScreen({
    super.key,
    required this.childId,
    required this.childName,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(aiInsightsProvider(childId));

    return Scaffold(
      backgroundColor: context.colors.bgLight,
      appBar: AppBar(
        title: Text('$childName\'s AI Insights', style: context.textStyles.heading2),
        backgroundColor: context.colors.bgLight,
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh_rounded),
            tooltip: 'Re-generate Insights',
            onPressed: () => ref
                .read(aiInsightsProvider(childId).notifier)
                .loadInsights(forceRefresh: true),
          ),
        ],
      ),
      body: state.isLoading
          ? Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  CircularProgressIndicator(color: context.colors.primary),
                  const SizedBox(height: AppSpacing.md),
                  Text('Gemini is analyzing child logs...', style: context.textStyles.bodyMuted),
                ],
              ),
            )
          : state.error != null
              ? _ErrorView(
                  message: state.error!,
                  onRetry: () => ref
                      .read(aiInsightsProvider(childId).notifier)
                      .loadInsights(),
                )
              : SingleChildScrollView(
                  padding: const EdgeInsets.all(AppSpacing.lg),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // ── Disclaimer Banner ──────────────────────────────────
                      Container(
                        padding: const EdgeInsets.all(AppSpacing.md),
                        margin: const EdgeInsets.only(bottom: AppSpacing.lg),
                        decoration: BoxDecoration(
                          color: context.colors.danger.withValues(alpha: 0.08),
                          borderRadius: BorderRadius.circular(AppRadius.lg),
                          border: Border.all(color: context.colors.danger.withValues(alpha: 0.25)),
                        ),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Icon(Icons.info_outline_rounded, color: context.colors.danger, size: 20),
                            const SizedBox(width: AppSpacing.md),
                            Expanded(
                              child: Text(
                                'MEDICAL DISCLAIMER: These insights are generated by AI based on child activity logs. They are educational only and do not replace professional medical advice, pediatrician diagnoses, or prescriptions.',
                                style: context.textStyles.caption.copyWith(
                                  color: context.colors.danger,
                                  fontWeight: FontWeight.w600,
                                  fontSize: 11,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),

                      // ── Insights Cards ─────────────────────────────────────
                      if (state.nutrition != null)
                        _InsightCard(
                          title: 'Nutrition & Meals',
                          icon: Icons.restaurant_rounded,
                          color: Colors.green.shade700,
                          data: state.nutrition!,
                        ),

                      if (state.sleep != null)
                        _InsightCard(
                          title: 'Sleep & Naps',
                          icon: Icons.nightlight_round_rounded,
                          color: Colors.indigo.shade700,
                          data: state.sleep!,
                        ),

                      if (state.hydration != null)
                        _InsightCard(
                          title: 'Hydration Intake',
                          icon: Icons.water_drop_rounded,
                          color: Colors.blue.shade700,
                          data: state.hydration!,
                        ),

                      if (state.medical != null)
                        _InsightCard(
                          title: 'Wellness & First-Aid Tips',
                          icon: Icons.medical_services_rounded,
                          color: Colors.red.shade700,
                          data: state.medical!,
                        ),

                      if (state.growth != null)
                        _InsightCard(
                          title: 'Growth Trajectory',
                          icon: Icons.trending_up_rounded,
                          color: Colors.teal.shade700,
                          data: state.growth!,
                        ),

                      if (state.nutrition == null &&
                          state.sleep == null &&
                          state.hydration == null &&
                          state.medical == null &&
                          state.growth == null)
                        _EmptyInsights(),
                    ],
                  ),
                ),
    );
  }
}

class _InsightCard extends StatelessWidget {
  final String title;
  final IconData icon;
  final Color color;
  final Map<String, dynamic> data;

  const _InsightCard({
    required this.title,
    required this.icon,
    required this.color,
    required this.data,
  });

  @override
  Widget build(BuildContext context) {
    final analysis = data['analysis'] as String? ?? '';
    final suggestionsList = (data['suggestions'] as List<dynamic>?) ?? [];

    return Container(
      margin: const EdgeInsets.only(bottom: AppSpacing.lg),
      decoration: BoxDecoration(
        color: context.colors.bgSurface,
        borderRadius: BorderRadius.circular(AppRadius.xl),
        border: Border.all(color: context.colors.border),
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(AppSpacing.sm),
                  decoration: BoxDecoration(
                    color: color.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(AppRadius.lg),
                  ),
                  child: Icon(icon, color: color, size: 24),
                ),
                const SizedBox(width: AppSpacing.md),
                Text(title, style: context.textStyles.labelBold.copyWith(fontSize: 16)),
              ],
            ),
            const SizedBox(height: AppSpacing.md),
            if (analysis.isNotEmpty)
              Text(
                analysis,
                style: context.textStyles.bodyMedium,
              ),
            if (suggestionsList.isNotEmpty) ...[
              const SizedBox(height: AppSpacing.md),
              const Divider(),
              const SizedBox(height: AppSpacing.sm),
              Text('Actionable Suggestions:', style: context.textStyles.labelBold.copyWith(fontSize: 13, color: color)),
              const SizedBox(height: AppSpacing.sm),
              ...suggestionsList.map((s) => Padding(
                    padding: const EdgeInsets.symmetric(vertical: 4),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Icon(Icons.check_circle_outline_rounded, color: color, size: 16),
                        const SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            s.toString(),
                            style: context.textStyles.bodySmall.copyWith(color: context.colors.textDark),
                          ),
                        ),
                      ],
                    ),
                  )),
            ],
          ],
        ),
      ),
    );
  }
}

class _EmptyInsights extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.xxl),
        child: Column(
          children: [
            Icon(Icons.insights_rounded, size: 64, color: context.colors.border),
            const SizedBox(height: AppSpacing.md),
            Text('No logs available yet', style: context.textStyles.labelBold),
            const SizedBox(height: 4),
            Text(
              'Once you or the caregiver log activities, sleep, nutrition, or growth, AI recommendations will show up here.',
              style: context.textStyles.caption,
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}

class _ErrorView extends StatelessWidget {
  final String message;
  final VoidCallback onRetry;

  const _ErrorView({required this.message, required this.onRetry});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.xxl),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.error_outline_rounded, size: 52, color: context.colors.danger),
            const SizedBox(height: AppSpacing.md),
            Text('Analysis Failed', style: context.textStyles.labelBold),
            const SizedBox(height: 8),
            Text(
              message,
              style: context.textStyles.caption,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppSpacing.lg),
            ElevatedButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh_rounded),
              label: const Text('Try Again'),
            ),
          ],
        ),
      ),
    );
  }
}
